pipeline {
    agent any

    tools {
        maven 'Maven3'
        jdk 'jdk21'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/asrafulmd12/Wipro-traning.git'
            }
        }

        stage('Build') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'mvn clean'
                }
            }
        }

        stage('Compile') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'mvn compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('Automation_Testing_Practice') {
                    bat 'mvn package'
                }
            }
        }


    }

    post {


        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}